#!/usr/bin/env python3
"""Generate functional Verilog models of combinational cells from a Liberty file.

    python3 lib2v.py cells.lib[.gz] [EXTRA_CELL ...] > cells.v

EXTRA_CELL names physical-only cells that are missing from the Liberty file
(e.g. sky130_fd_sc_hd__tapvpwrvgnd_1); they become empty port-less modules.

Every cell with at least one output pin that has a `function` attribute
becomes a module of continuous assigns.  Cells without any function (taps,
fillers, decaps, diodes) become empty modules with their pins, so physical
cells in a netlist still elaborate.  Sequential cells (ff/latch groups) are
skipped: this is for gate-level simulation of combinational netlists only.

Liberty function syntax handled: ! ' (not), & * space (and), | + (or),
^ (xor), parentheses, constants 0/1.
"""
import gzip
import re
import sys


def read(path):
    op = gzip.open if path.endswith(".gz") else open
    with op(path, "rt") as f:
        return f.read()


def blocks(text, kind):
    """Yield (name, body) for each `kind (name) { ... }` group, brace-matched."""
    for m in re.finditer(rf"\b{kind}\s*\(\s*\"?([\w\[\]]+)\"?\s*\)\s*{{", text):
        depth, i = 1, m.end()
        while depth:
            c = text[i]
            depth += (c == "{") - (c == "}")
            i += 1
        yield m.group(1), text[m.end():i - 1]


def to_verilog(expr):
    e = expr.strip().strip('"')
    e = re.sub(r"(\w+)\s*'", r"!\1", e)                       # postfix ' -> prefix !
    e = e.replace("*", "&").replace("+", "|").replace("!", "~")
    # implicit AND: whitespace between two operands
    e = re.sub(r"(?<=[\w)])\s+(?=[\w(~])", " & ", e)
    e = re.sub(r"\b([01])\b", r"1'b\1", e)
    return e


def main():
    text = read(sys.argv[1])
    out = ["// generated by lib2v.py from " + sys.argv[1].split("/")[-1],
           "`timescale 1ns/1ps"]
    for cell, body in blocks(text, "cell"):
        if re.search(r"\b(ff|latch|statetable)\s*\(", body):
            continue
        ins, outs = [], []
        for pin, pbody in blocks(body, "pin"):
            d = re.search(r"direction\s*:\s*\"?(\w+)", pbody)
            f = re.search(r"\bfunction\s*:\s*\"([^\"]*)\"", pbody)
            if d and d.group(1) == "output":
                outs.append((pin, f.group(1) if f else None))
            elif d and d.group(1) in ("input", "inout"):
                ins.append(pin)
        ports = [p for p, _ in outs] + ins
        out.append(f"module {cell} ({', '.join(ports)});")
        for p, fn in outs:
            out.append(f"  output {p};")
        for p in ins:
            out.append(f"  input {p};")
        for p, fn in outs:
            if fn:
                out.append(f"  assign {p} = {to_verilog(fn)};")
        out.append("endmodule\n")
    # physical-only cells that some libraries leave out of the Liberty file
    for extra in sys.argv[2:]:
        out.append(f"module {extra} ();\nendmodule\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
