#!/usr/bin/env python3
"""Assemble the paper's result tables from the raw sweep, power and error files.

    python syn/final_tables.py        # writes results/final_tables.md

Sources (all in results/):
  ppa_<plat>_synth[_truncW]_syn.csv        synthesis area (primary area metric)
  ppa_<plat>_cts[_trunc24].csv             tight clock target: best achieved delay
  ppa_<plat>_cts[_trunc24]_relax.csv       target = 1.1x achieved delay: area after CTS
  power_relax.txt                          gate-level energy at the relaxed targets
  error_block.csv, error_chain4096.csv     accuracy study
"""
import csv
import re
from pathlib import Path

RES = Path(__file__).resolve().parents[1] / "results"
FMTS = ["e2m1", "e2m3", "e3m2", "int8", "e4m3", "e5m2"]
NAME = {"e2m1": "MXFP4 E2M1", "e2m3": "MXFP6 E2M3", "e3m2": "MXFP6 E3M2",
        "int8": "MXINT8", "e4m3": "MXFP8 E4M3", "e5m2": "MXFP8 E5M2"}


def csv_map(name, key="area"):
    p = RES / name
    if not p.exists():
        return {}
    with open(p) as f:
        return {r["config"].removesuffix("_syn").removesuffix("_relax"): float(r[key])
                for r in csv.DictReader(f) if r.get(key) not in (None, "", "None")}


def energy(plat):
    out = {}
    p = RES / "power_relax.txt"
    for line in p.read_text().splitlines() if p.exists() else []:
        m = re.match(rf"{plat} POWER (\S+) .*mismatches=(\d+) .*energy_pJ_per_op=([\d.eE+-]+)", line)
        if m:
            assert m.group(2) == "0", f"gate-level mismatch in {line}"
            out[m.group(1).removesuffix("_relax")] = float(m.group(3))
    return out


def cfg(f, pipe="0000", k=32, pol=""):
    return f"{pol}{f}x{f}_k{k}_p{pipe}"


def r(x, y, nd=2):
    return f"{x / y:.{nd}f}" if x and y else "-"


def table(head, rows):
    s = "| " + " | ".join(head) + " |\n|" + "|".join("---" if i == 0 else "---:" for i in range(len(head))) + "|\n"
    return s + "".join("| " + " | ".join(str(c) for c in row) + " |\n" for row in rows)


def main():
    md = ["# Final result tables", "",
          "Generated by `syn/final_tables.py`.  Exact = `mx_dotp`; trunc*W* = "
          "`mx_dotp_trunc` with a *W*-bit window.  Ratios < 1: exact is cheaper.", ""]

    # ---- Table 1: synthesis area, both processes
    md += ["## T1. Logic area after synthesis (K=32)", ""]
    for plat in ("asap7", "sky130hd"):
        ex = csv_map(f"ppa_{plat}_synth_syn.csv")
        t24 = csv_map(f"ppa_{plat}_synth_trunc24_syn.csv")
        t32 = csv_map(f"ppa_{plat}_synth_trunc32_syn.csv")
        rows = []
        for f in FMTS:
            for pipe in ("0000", "1111"):
                c = cfg(f, pipe)
                rows.append([NAME[f], "comb" if pipe == "0000" else "4-stage",
                             f"{ex.get(c, 0):,.0f}", f"{t24.get('trunc24_' + c, 0):,.0f}",
                             f"{t32.get('trunc32_' + c, 0):,.0f}",
                             r(ex.get(c), t24.get("trunc24_" + c)), r(ex.get(c), t32.get("trunc32_" + c))])
        unit = "um^2"
        md += [f"### {plat} ({unit})", "",
               table(["format", "pipe", "exact", "trunc24", "trunc32", "exact/t24", "exact/t32"], rows), ""]

    # ---- Table 2: block size trend
    md += ["## T2. Block size K (MXFP8 E4M3, 4-stage, synthesis)", ""]
    rows = []
    for k in (8, 16, 32, 64):
        row = [k]
        for plat in ("asap7", "sky130hd"):
            ex = csv_map(f"ppa_{plat}_synth_syn.csv")
            t24 = csv_map(f"ppa_{plat}_synth_trunc24_syn.csv")
            c = cfg("e4m3", "1111", k)
            row.append(r(ex.get(c), t24.get("trunc24_" + c)))
        rows.append(row)
    md += [table(["K", "asap7 exact/t24", "sky130hd exact/t24"], rows), ""]

    # ---- Table 3/4: timing, area after CTS, energy
    for plat, fmts, unit_t, unit_e in (("asap7", FMTS, "ps", "pJ"), ("sky130hd", ["e2m1", "e5m2"], "ns", "pJ")):
        dly_e = csv_map(f"ppa_{plat}_cts.csv", "delay")
        dly_t = csv_map(f"ppa_{plat}_cts_trunc24.csv", "delay")
        ar_e = csv_map(f"ppa_{plat}_cts_relax.csv")
        ar_t = csv_map(f"ppa_{plat}_cts_trunc24_relax.csv")
        en = energy(plat)
        rows = []
        for f in fmts:
            c, t = cfg(f), "trunc24_" + cfg(f)
            rows.append([NAME[f],
                         f"{dly_e.get(c, 0):.4g} / {dly_t.get(t, 0):.4g}", r(dly_e.get(c), dly_t.get(t)),
                         f"{ar_e.get(c, 0):,.0f} / {ar_t.get(t, 0):,.0f}", r(ar_e.get(c), ar_t.get(t)),
                         f"{en.get(c, 0):.3g} / {en.get(t, 0):.3g}", r(en.get(c), en.get(t))])
        md += [f"## T3-{plat}. Single-cycle K=32: delay, post-CTS area, energy (exact / trunc24)", "",
               f"Delay: tight target (best achieved, {unit_t}).  Area and energy: target = 1.1x achieved "
               f"delay, after CTS; energy per dot product ({unit_e}) from gate-level simulation of "
               "the netlist on MX GEMM data (512 vectors, all bit-exact).", "",
               table(["format", "delay", "ratio", "area", "ratio", "energy", "ratio"], rows), ""]

    # ---- Table 5: accuracy
    def err_rows(name):
        p = RES / name
        with open(p) as f:
            return list(csv.DictReader(f))
    blk = err_rows("error_block.csv")
    chn = err_rows("error_chain4096.csv")
    rows = []
    for f in FMTS:
        def b(dist, w):
            x = next(x for x in blk if x["fmt"] == f and x["dist"] == dist and x["policy"] == f"trunc{w}")
            return f"{float(x['differs_pct']):.1f}%"

        def c(dist, pol):
            x = next(x for x in chn if x["fmt"] == f and x["dist"] == dist and x["policy"] == pol)
            return f"{float(x['p99_rel_err']):.1e}"
        rows.append([NAME[f], b("gauss", 24), b("gauss", 32), b("outlier", 24),
                     c("gauss", "exact"), c("gauss", "trunc24"),
                     c("outlier", "exact"), c("outlier", "trunc24"), c("outlier", "trunc28")])
    md += ["## T4. Accuracy of anchored truncation", "",
           "Block: single K=32 block with c at the dot product's magnitude; % of results that "
           "differ from exact.  Chain: 4096-long GEMM row (r fed back as c); p99 relative "
           "error vs the true value of the MX-quantised inputs.  Synthetic data only.", "",
           table(["format", "block gauss W24", "block gauss W32", "block outlier W24",
                  "chain gauss exact", "chain gauss W24", "chain outlier exact",
                  "chain outlier W24", "chain outlier W28"], rows), ""]

    out = RES / "final_tables.md"
    out.write_text("\n".join(md))
    print(out.read_text())


if __name__ == "__main__":
    main()
